# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'verbose_name': 'Area',
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Curriculos',
                'verbose_name': 'Curriculo',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'verbose_name': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('siglas', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'verbose_name': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(max_length=60)),
                ('detalle', models.TextField(max_length=2)),
                ('titulo', models.CharField(max_length=40)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planilla.Curriculo')),
            ],
            options={
                'verbose_name_plural': 'Rubros',
                'verbose_name': 'Rubro',
            },
        ),
        migrations.AddField(
            model_name='curriculo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planilla.Empleado'),
        ),
        migrations.AddField(
            model_name='area',
            name='empleados',
            field=models.ManyToManyField(blank=True, null=True, to='planilla.Empleado'),
        ),
        migrations.AddField(
            model_name='area',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planilla.Empresa'),
        ),
    ]
